version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: epitrello_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"  # host:container
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: